### ISSUE TITLE
Styling v1

### ISSUE THREAD

**Issue by sertmer** [sertmer/-DUNZO-#10]
```
As A:
- user trying to get things done

When I:
- use the app

I want:
- to interact with a beautiful, functional application

So that:
- I can enjoy getting things done

```
**• Subtasks •**

- [x] Style each task
- [x] Style header
- [x] Choose and implement font family
- [ ] Style AddTask
- [ ] fix router issues

**• Notes •**
-
