### ISSUE TITLE
Set  Up - Configuration and Installation of initial Dependencies

### ISSUE THREAD

**Issue by sertmer** [sertmer/-DUNZO-#2]
```
As A:
- Front End Dev

When I:
- Build the Application

I want:
-To have all the dopest dependencies

So that:
- I can design, build, and test the dopest -DUNZO- app around town

```
**• Subtasks •**
- [x] Create React App
- [x] Install the React Testing Library 
- [x] Install proptypes
- [x] Install SCSS
- [x] Organize File Structure
- [x] Create README
- [x] Install Router

**• Notes •**
- Using React Testing Library to strengthen my understanding of DOM changes as tests
- Use Hooks and Context API to replace Redux && Strengthen understanding of modern React capabilities
