### ISSUE TITLE
Design Component Structure and Responsibilities 

### ISSUE THREAD

**Issue by sertmer** [sertmer/-DUNZO-#3]
```
As A:
_ Front End Dev

I want:
_ To Design the component structure and each components state and behavior

So that:
_ I have documentation and a clear path towards MVP

```
**• Subtasks •**

- [x] Wireframe Component Structure
- [x] Determine Component Methods
- [x] Determine Component State
- [x] Document and add to README

**• Notes •**
- inVision? Add link to project readme
