### ISSUE TITLE
Add and display tasks

### ISSUE THREAD

**Issue by sertmer** [sertmer/-DUNZO-#7]
```
As A:
- human interested in gettin' ish done

When I:
- use the app

I want:
- to be able to navigate to the right place

So that:
- I can get things done

```
**• Subtasks •**

- [x] Build initial App component
- [x] Build initial Tasks component
- [x] Build initial Task component
- [x] Build initial addTask component
- [x] Build initial routes for all components
- [x] Add snapshot tests
