### ISSUE TITLE
Store tasks in local storage

### ISSUE THREAD

**Issue by sertmer** [sertmer/-DUNZO-#9]
```
As A:
- user trying to get things done

I want:
- to have my tasks persist no matter where I move within the App

So that:
- I can get those tasks done.

```
**• Subtasks •**

- [ ] - restructure task to be an object like so:
```
{
  title: 'string',
  id: num,
  age: num,
  associatedGoals: [ 'string', ' ', etc],
  highPriority: boolean,
  complete: boolean,
  originDate: datestring
}
```
- [ ] save the whole array of tasks to local storage
- [ ] get tasks out of storage and display on page

**• Notes •**
-
